version: '3.3'
services:

  alfresco:
    image: consiglionazionalericerche/alfresco-community-erecruitment:latest
    read_only: true
    ports:
      - 9080:8080
    command: sh -c 'catalina.sh jpda run'
    environment:
      JAVA_OPTS: '-Xmx2g'
      LANG: en_US.UTF-8
      LANGUAGE: en_US:en
      LC_ALL: en_US.UTF-8
      SERVICE_TAGS: webapp
      SERVICE_NAME: alfresco-community-erecruitment
    labels:
      - SERVICE_NAME=alfresco-community-erecruitment
    volumes:
      - ./alfresco-global.properties:/usr/local/tomcat/shared/classes/alfresco-global.properties
      - ./contentstore:/content_store/
      - /tmp
      - /usr/local/tomcat/temp/
      - ./alfresco_logs:/usr/local/tomcat/logs/
      - /usr/local/tomcat/conf/Catalina/
      - /usr/local/tomcat/work/
    links:
      - pgalfresco:pgalfresco

  pgalfresco:
    image: postgres:9.2
    environment:
      - POSTGRES_PASSWORD=alfrescopw
      - POSTGRES_USER=alfresco
      - POSTGRES_DB=alfresco
      - PG_WORK_MEM=64MB
      - PG_MAINTENANCE_WORK_MEM=512MB
    command: postgres -c max_connections=300 -c log_min_messages=LOG -c 'shared_buffers=512MB'
    volumes:
      - ./pgdata:/var/lib/postgresql/data/
    expose:
      - "5432"

  solr4:
    image: consiglionazionalericerche/alfresco-solr4-erecruitment:latest
    read_only: true
    environment:
      - '-Xmx1g'
    volumes:
      - /usr/local/tomcat/
      - /solr-data-store/
      - /solr4-content/
      - /solr4-models/
    links:
      - alfresco:my-alfresco

  cool-jconon-onb:
    image: cool-jconon-onb:latest
    environment:
      - REPOSITORY_BASE_URL=http://alfresco:8080/alfresco/
      - SERVER_SERVLET_CONTEXT-PATH=/
      - SPRING_PROFILES_ACTIVE=prod,onb
      - USER_ADMIN_PASSWORD=admin
      - LANG=it_IT.UTF-8
      - LANGUAGE=it_IT:it
      - LC_ALL=it_IT.UTF-8
      - 'TZ=Europe/Rome'
    links:
      - alfresco:alfresco
    labels:
      - SERVICE_NAME=cool-jconon-onb

  nginx:
    image: nginx:1.13-alpine
    ports:
      - 80:80
      - 443:443
    environment:
      - 'FASTCGI_READ_TIMEOUT=300s'
    links:
      - alfresco:alfresco
      - solr4:solr4
      - cool-jconon-onb:cool-jconon-onb
    depends_on:
      - alfresco
      - solr4
      - cool-jconon-onb
    labels:
      SERVICE_NAME: nginx
    read_only: true
    volumes:
      - ./conf.d/:/etc/nginx/conf.d/
      - /var/cache/nginx/
      - /var/run/
